name: Globe Access API CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
          node-version: 20
    - name: Build the Docker image
      uses: docker/build-push-action@v2
    - run: npm ci
    # - run: npm test
    - run: npm run docker:prod